# Generated by Django 5.2.16 on 2026-08-09 14:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('cover_image', models.ImageField(upload_to='book_covers/')),
                ('quote', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2)),
                ('category', models.CharField(choices=[('fiction', 'Fiction'), ('manga', 'Manga'), ('manhwa', 'Manhwa'), ('classic', 'Classic')], default='fiction', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='book_pdfs/')),
                ('external_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
