# Generated by Django 5.2.16 on 2026-08-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('manga', 'Manga'), ('manhwa', 'Manhwa'), ('classic', 'Classics'), ('mystery', 'Mystery & Thriller'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('sci-fi', 'Science Fiction')], default='fiction', max_length=20),
        ),
    ]
