# Generated by Django 5.2.17 on 2026-08-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_contact_desc_contact_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notification',
            name='icon',
            field=models.CharField(choices=[('fa-book', 'Book'), ('fa-info-circle', 'Info'), ('fa-check-circle', 'Success'), ('fa-exclamation-triangle', 'Warning'), ('fa-user-plus', 'New User'), ('fa-star', 'Star')], default='fa-info-circle', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(default='fa-info-circle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
