# Generated by Django 5.2.17 on 2026-08-25 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_notification_options_notification_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, choices=[('book', 'Book'), ('info', 'Info'), ('check', 'Success'), ('warning', 'Warning'), ('user', 'New User'), ('star', 'Star')], default='info', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='home_notifi_user_id_29f498_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='home_notifi_created_b9cbc6_idx'),
        ),
    ]
