# Generated by Django 5.2.17 on 2026-08-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contact_description_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('manga', 'Manga'), ('manhwa', 'Manhwa'), ('classic', 'Classics'), ('mystery', 'Mystery & Thriller'), ('romance', 'Romance'), ('fantasy', 'Fantasy'), ('sci-fi', 'Science Fiction'), ('novel', 'Novel')], default='fiction', max_length=20),
        ),
    ]
