# Generated by Django 5.2.17 on 2026-08-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_notification_options_notification_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.CharField(blank=True, choices=[('fa-book', 'Book'), ('fa-info-circle', 'Info'), ('fa-check-circle', 'Success'), ('fa-exclamation-triangle', 'Warning'), ('fa-user-plus', 'New User'), ('fa-star', 'Star')], default='fa-info-circle', max_length=35, null=True),
        ),
    ]
